name: expense_repository
description: tracker app
public_to: "none"
version: 0.1.1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^4.16.0
  cloud_firestore: ^4.9.2

dev_dependencies:
flutter_test:
  sdk: flutter

flutter_lints: ^3.0.0

flutter:
# The following line ensures that the Material Icons font is
# included with your application, so that you can use the icons in
# the material Icons class.
uses-material-design: true
